static_pages:
  help:
    link1: "https://www.google.com.vn/"
Member:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
  size:
    index: 50
    avatar: 80
links:
  avatar_email: "http://gravatar.com/emails"
paginate:
  per_page: 7
Story:
  name:
    maximum: 20
  image:
    maximum: 20
  describe:
    minimum: 20
Comment:
  content: 140
